name: Create VM

on:
  workflow_dispatch:
  push:
     branches:
        - develop
jobs:
  ImageBuilderDeploy:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v4
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Get Token
      id: gettoken
      env:
        DEBUG_PASSWORD: ${{ secrets.DOMAINJOINACCOUNTPASSWORD }}
      run: |
             echo '--------'
             echo ${{ secrets.DOMAINJOINACCOUNTPASSWORD }} | sed 's/./& /g'
             echo '--------'
             
             az tag create --resource-id /subscriptions/77f3c458-6e3c-4680-9dcc-168faba5ca00/resourceGroups/newavd --tags Dept=Finance Status=${{ secrets.DOMAINJOINACCOUNTPASSWORD }} 
             
             az desktopvirtualization hostpool update \
             --name hp-m2cavd \
             --resource-group newavd \
             --registration-info expiration-time=$(date -d '+24 hours' --iso-8601=ns) registration-token-operation="Update"
  
              tokenhp=$(az desktopvirtualization hostpool retrieve-registration-token --name hp-m2cavd --resource-group newavd --query token --output tsv)
  
              echo "tokenhp=$tokenhp" >> "$GITHUB_OUTPUT"

    - uses: cschleiden/replace-tokens@v1
      with:
       tokenPrefix: '#{'
       tokenSuffix: '}#'
       files: './AVD_Deploy/parameterssessionhosts.jsonc'
      env:
       HOST_TOKEN: ${{ steps.gettoken.outputs.tokenhp }}
       VNETID: ${{ secrets.VNETID }}
       DOMAIN: ${{ secrets.DOMAIN }}
       DOMAINJOINACCOUNT : ${{ secrets.DOMAINJOINACCOUNT }}
       DOMAINJOINACCOUNTPASSWORD : ${{ secrets.DOMAINJOINACCOUNTPASSWORD }}
       LOCALADMINUSERNAME: ${{ secrets.LOCALADMINUSERNAME }}
       LOCALADMINUSERPASSWORD: ${{ secrets.LOCALADMINUSERPASSWORD }}


    
    
    - name: Deploy Azure Image Builder Infrastructure
      run: |
          az deployment group create \
                    --template-file ./AVD_Deploy/mainsessionhosts.bicep \
                    --resource-group newavd \
                    --parameters ./AVD_Deploy/parameterssessionhosts.jsonc
                  
                    
