name: Azure Image Builder - Build and Publish Image Template

on:
  workflow_dispatch:
  push:
     branches:
        - develop
jobs:
  ImageBuilderDeploy:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v4
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Image Builder Infrastructure
      run: |
          az deployment group create \
                    --template-file ./AVD/main.bicep \
                    --resource-group AVD \
                    

  #ImageBuilderRun:
  #  needs: ImageBuilderDeploy
  #  runs-on: ubuntu-latest
   
  #  steps:   
  #  - uses: actions/checkout@v4
  #  - name: Azure login
  #    uses: azure/login@v2
  #    with:
  #      creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  #  - name: 'Run Azure Image Builder'
  #    run: |
  #        az image builder run -n templatervr -g testrvr2 --no-wait --verbose
  #        az image builder wait -n templatervr -g testrvr2 --custom "lastRunStatus.runState!='Running'" --verbose
