name: Create VM

on:
  workflow_dispatch:
  push:
     branches:
        - develop
jobs:
  ImageBuilderDeploy:
    runs-on: ubuntu-latest
    steps:   
    - uses: actions/checkout@v4
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: Get Token
      run: |
             az desktopvirtualization hostpool update \
             --name hp-m2cavd \
             --resource-group newavd \
             --registration-info expiration-time=$(date -d '+24 hours' --iso-8601=ns) registration-token-operation="Update"
  
             $tokenhp=$(az desktopvirtualization hostpool retrieve-registration-token \
              --name hp-m2cavd \
              --resource-group newavd \
              --query token --output tsv)
  
              echo $tokenhp : $tokenhp

    - uses: cschleiden/replace-tokens@v1
      with:
       tokenPrefix: '#{'
       tokenSuffix: '}#'
       files: './AVD_Deploy/parameterssessionhosts.jsonc'


    - name: Deploy Azure Image Builder Infrastructure
      run: |
          echo ${{ env.tokenhp }}
          cat ./AVD_Deploy/parameterssessionhosts.jsonc
    
    #- name: Deploy Azure Image Builder Infrastructure
    #  run: |
    #      az deployment group create \
    #                --template-file ./AVD_Deploy/mainsessionhosts.bicep \
    #                --resource-group newavd \
    #                --parameters ./AVD_Deploy/parameterssessionhosts.jsonc
                    
#az deployment group create --resource-group newavd --template-file ./mainsessionhosts.bicep --parameters ./parameterssessionhosts.jsonc --name "DeploySessionHosts_fdsfds"

  #ImageBuilderRun:
  #  needs: ImageBuilderDeploy
  #  runs-on: ubuntu-latest
   
  #  steps:   
  #  - uses: actions/checkout@v4
  #  - name: Azure login
  #    uses: azure/login@v2
  #    with:
  #      creds: ${{ secrets.AZURE_CREDENTIALS }}
        
  #  - name: 'Run Azure Image Builder'
  #    run: |
  #        az image builder run -n templatervr -g testrvr2 --no-wait --verbose
  #        az image builder wait -n templatervr -g testrvr2 --custom "lastRunStatus.runState!='Running'" --verbose
