name: Azure Image Builder - Build and Publish Image Template

on:
  workflow_dispatch:
  push:
     branches:
        - develop

env:
  Image_RG: testrvr2
  Template_Name: TemplateImgRVR
  Host_RG: newavd
  Host_Pool: hp-m2cavd
  VM_RG: newavd

jobs:
  ImageBuilderDeploy:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.deploy.outputs.IMAGE_ID }}
    steps:   
    - uses: actions/checkout@v4
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Image Builder Infrastructure
      id: deploy
      run: |
          result=$(az deployment group create --template-file ./CustomImage/main.bicep --resource-group $Image_RG --parameters ./CustomImage/parameters.storageplusvgInfo.json | ConvertFrom-Json)
          echo ESTE es el resultado $result
          IMAGE_ID=$(echo $result | jq -r '.properties.outputs.imageId.value')
          echo Esta es la imagen $IMAGE_ID
          echo "IMAGE_ID=$IMAGE_ID" >> "$GITHUB_OUTPUT"

  ImageBuilderRun:
    needs: ImageBuilderDeploy
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.run.outputs.IMAGE_ID }}
    env:
      IMAGE_ID: ${{ needs.ImageBuilderDeploy.outputs.output1 }}
    steps:   
    - uses: actions/checkout@v4
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Run Azure Image Builder'
      id: run
      run: |
          az image builder show -n $Template_Name -g $Image_RG
          echo "IMAGE_ID=$IMAGE_ID" >> "$GITHUB_OUTPUT"
#          az image builder run -n $Template_Name -g $Image_RG --no-wait --verbose
#          az image builder wait -n $Template_Name -g $Image_RG --custom "lastRunStatus.runState!='Running'" --verbose

  VmCreation:
    needs: [ImageBuilderRun]
    runs-on: ubuntu-latest
    env:
      IMG: ${{ needs.ImageBuilderRun.outputs.output1 }}
    steps:   
        - uses: actions/checkout@v4
        - name: Azure login
          uses: azure/login@v2
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
        - name: Get Token
          id: gettoken
          run: |
                 az desktopvirtualization hostpool update \
                 --name $Host_Pool \
                 --resource-group $Host_RG \
                 --registration-info expiration-time=$(date -d '+24 hours' --iso-8601=ns) registration-token-operation="Update"
      
                  tokenhp=$(az desktopvirtualization hostpool retrieve-registration-token --name $Host_Pool --resource-group $Host_RG --query token --output tsv)
      
                  echo "tokenhp=$tokenhp" >> "$GITHUB_OUTPUT"
    
        - uses: cschleiden/replace-tokens@v1
          with:
           tokenPrefix: '#{'
           tokenSuffix: '}#'
           files: './AVD_Deploy/parameterssessionhosts.jsonc'
          env:
           HOST_TOKEN: ${{ steps.gettoken.outputs.tokenhp }}
           VNETID: ${{ secrets.VNETID }}
           DOMAIN: ${{ secrets.DOMAIN }}
           DOMAINJOINACCOUNT : ${{ secrets.DOMAINJOINACCOUNT }}
           DOMAINJOINACCOUNTPASSWORD : ${{ secrets.DOMAINJOINACCOUNTPASSWORD }}
           LOCALADMINUSERNAME: ${{ secrets.LOCALADMINUSERNAME }}
           LOCALADMINUSERPASSWORD: ${{ secrets.LOCALADMINUSERPASSWORD }}
           IMAGE_ID: ${{ env.IMG }}
    
    
        - name: Deploy Azure Image Builder Infrastructure
          run: |
               az deployment group create \
                         --template-file ./AVD_Deploy/mainsessionhosts.bicep \
                         --resource-group $VM_RG \
                         --parameters ./AVD_Deploy/parameterssessionhosts.jsonc        
        
        - name: Clean up Template
          run: |
              az image builder delete -n $Template_Name -g $Image_RG --verbose